/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:ce9bc047-9ddb-48b3-8fb0-252ae800beb2",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_BzbTBrNuC",
  aws_user_pools_web_client_id: "3fmalgdeh9v5kpaubg9npdnp88",
  oauth: {
    domain: "reactcardgames.auth.us-east-1.amazoncognito.com",
    scope: ["email", "profile", "openid"],
    redirectSignIn:
      "https://thezhongfamily.net/,http://localhost:3000/,https://reactcardgames.auth.us-east-1.amazoncognito.com/oauth2/idpresponse",
    redirectSignOut: "https://thezhongfamily.net/,http://localhost:3000/",
    responseType: "code",
  },
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: ["google"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
